#!/usr/bin/env ruby
# EXAMPLE: bin/dehenzify app/lib/stats
require 'bundler/setup'
require 'dehenzify'

file_or_path = ARGV[0]

exit(1) if file_or_path.nil?

files =
  if file_or_path.end_with?('.rb')
    [file_or_path]
  else
    Pathname.new(file_or_path).glob('**/*.rb')
  end

files.each do |file_path|
  dehenzifier = Dehenzify::Dehenzifier.new(file_path)
  extracted_sources = dehenzifier.run!
  extracted_sources.each do |extracted_source|
    extracted_source.write!
  end
end

exit(0)
